export default {
  index: "Vue d'ensemble",
  'newsletter-catalogue': 'Newsletter catalogue automatique',
  'instagram-publication-produits': 'Publication produits Instagram',
  'login-passwordless': 'Login passwordless Supabase',
  'espace-vendeur': 'Espace vendeur',
  'vitrine-vendeur-publique': 'Vitrine vendeur publique',
  'badge-vendeur-premium': 'Badge vendeur premium',
  'catalogue-produits': 'Catalogue produits',
  'mise-en-relation-whatsapp': 'Mise en relation WhatsApp',
  'produits-mis-en-avant': 'Produits mis en avant',
  'produits-affilies': 'Produits affilies',
  'back-office-admin-ia': 'Back-office admin et IA',
  'back-office-utilisateurs': 'Back-office utilisateurs',
  'analyse-ia-produit': 'Analyse IA produit',
  'blog-mdx': 'Blog MDX',
  'homepage-acquisition': 'Homepage et acquisition',
  'seo-sitemap-tracking': 'SEO, tracking et partage',
  'pipeline-images': 'Pipeline images',
  'proxy-image-cache-media': 'Proxy image et cache media',
  'revalidation-cache-isr': 'Revalidation cache ISR',
  'data-supabase-apis': 'Data Supabase et APIs',
  'carte-routes-api': 'Carte des routes API',
  'securite-permissions': 'Securite et permissions',
  'deploiement-configuration-externe': 'Deploiement et configuration',
  'conventions-ui-contenu': 'Conventions UI et contenu',
  'operations-scripts': 'Operations et scripts'
}
